### ISSUE TITLE
The judge status of the first record always remains fetched 

### ISSUE THREAD

**Issue by zzhou612** [joint-online-judge/cb4#12]
After restarting cb4 or jd4, the first submission of any problem will not be handled properly. The judge status of the first-submission record will always remain fetched.  If the cb4 is restarted, than the former fetched record will be handled, but still, the first submission remains fetched.

Currently, we need to submit several dump submissions in the test domain after restarting cb4 or jd4 to prevent the students from confronting this issue. Since I hate doing this over and over again, I think we need to solve this issue.

**Comment by tripack45** [comment]
I second this. Though you should assign that task to Oliver G.

**Comment by tc-imba** [comment]
Fixed #13

**Comment by zzhou612** [comment]
LYHTQL LYHKBQW
