### ISSUE TITLE
Declare language in the `config.yaml` rather than setting it by hand when submitting

### ISSUE THREAD

**Issue by linsyking** [joint-online-judge/cb4#61]
Tools like JOJ-Submitter has to know the language before I submit. Can we directly declare the language in the config files?

**Comment by BoYanZh** [comment]
Multiple languages can be declared in one problem, the submitter need to tell OJ which one to use. For now there is no default language option for a problem in cb4.

**Comment by linsyking** [comment]
is it better to allow one language for one exercise?

**Comment by BoYanZh** [comment]
Some courses do not force the language used in one problem. Students have to choose.
